# Form implementation generated from reading ui file '.\UI\design_setup.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogSetup(object):
    def setupUi(self, DialogSetup):
        DialogSetup.setObjectName("DialogSetup")
        DialogSetup.resize(581, 366)
        font = QtGui.QFont()
        font.setFamily("Rutenia2008VasylChebanyk")
        DialogSetup.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSetup)
        self.buttonBox.setGeometry(QtCore.QRect(220, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Reset|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(DialogSetup)
        self.buttonBox.accepted.connect(DialogSetup.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSetup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSetup)

    def retranslateUi(self, DialogSetup):
        _translate = QtCore.QCoreApplication.translate
        DialogSetup.setWindowTitle(_translate("DialogSetup", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSetup = QtWidgets.QDialog()
    ui = Ui_DialogSetup()
    ui.setupUi(DialogSetup)
    DialogSetup.show()
    sys.exit(app.exec())
