# Form implementation generated from reading ui file '.\UI\MQTT_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 360)
        MainWindow.setMinimumSize(QtCore.QSize(720, 360))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon\mqtt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(256, 256))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    font-family: \"Rutenia2008VasylChebanyk\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    font-size: 15px;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(61, 0, 255, 255));\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 6px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(61, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size: 15px\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.lneDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.lneDisplay.setObjectName("lneDisplay")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lneDisplay)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblIconConnect = QtWidgets.QLabel(self.centralwidget)
        self.lblIconConnect.setMaximumSize(QtCore.QSize(24, 24))
        self.lblIconConnect.setText("")
        self.lblIconConnect.setPixmap(QtGui.QPixmap("icon/checkNo.jpg"))
        self.lblIconConnect.setScaledContents(True)
        self.lblIconConnect.setObjectName("lblIconConnect")
        self.gridLayout_2.addWidget(self.lblIconConnect, 0, 0, 1, 1)
        self.pbtnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pbtnConnect.setObjectName("pbtnConnect")
        self.gridLayout_2.addWidget(self.pbtnConnect, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.pbtnSettings = QtWidgets.QPushButton(self.centralwidget)
        self.pbtnSettings.setObjectName("pbtnSettings")
        self.gridLayout_2.addWidget(self.pbtnSettings, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblControl = QtWidgets.QLabel(self.centralwidget)
        self.lblControl.setObjectName("lblControl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblControl)
        self.pbtnOnOff = QtWidgets.QPushButton(self.centralwidget)
        self.pbtnOnOff.setObjectName("pbtnOnOff")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pbtnOnOff)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblDisplay = QtWidgets.QLabel(self.centralwidget)
        self.lblDisplay.setObjectName("lblDisplay")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblDisplay)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblLuminocity = QtWidgets.QLabel(self.centralwidget)
        self.lblLuminocity.setObjectName("lblLuminocity")
        self.gridLayout.addWidget(self.lblLuminocity, 0, 0, 1, 1)
        self.lcdLuminocity = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdLuminocity.setObjectName("lcdLuminocity")
        self.gridLayout.addWidget(self.lcdLuminocity, 0, 1, 1, 1)
        self.lblLux = QtWidgets.QLabel(self.centralwidget)
        self.lblLux.setObjectName("lblLux")
        self.gridLayout.addWidget(self.lblLux, 0, 2, 1, 1)
        self.lblPressure = QtWidgets.QLabel(self.centralwidget)
        self.lblPressure.setObjectName("lblPressure")
        self.gridLayout.addWidget(self.lblPressure, 1, 0, 1, 1)
        self.lcdPressure = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdPressure.setObjectName("lcdPressure")
        self.gridLayout.addWidget(self.lcdPressure, 1, 1, 1, 1)
        self.lblPascal = QtWidgets.QLabel(self.centralwidget)
        self.lblPascal.setObjectName("lblPascal")
        self.gridLayout.addWidget(self.lblPascal, 1, 2, 1, 1)
        self.lblTemperature = QtWidgets.QLabel(self.centralwidget)
        self.lblTemperature.setObjectName("lblTemperature\n"
"")
        self.gridLayout.addWidget(self.lblTemperature
, 2, 0, 1, 1)
        self.lcdTemperature = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTemperature.setObjectName("lcdTemperature")
        self.gridLayout.addWidget(self.lcdTemperature, 2, 1, 1, 1)
        self.lblDegrees = QtWidgets.QLabel(self.centralwidget)
        self.lblDegrees.setObjectName("lblDegrees")
        self.gridLayout.addWidget(self.lblDegrees, 2, 2, 1, 1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.gridLayout)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblState = QtWidgets.QLabel(self.centralwidget)
        self.lblState.setObjectName("lblState")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblState)
        self.lneState = QtWidgets.QLineEdit(self.centralwidget)
        self.lneState.setObjectName("lneState")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lneState)
        self.lblError = QtWidgets.QLabel(self.centralwidget)
        self.lblError.setObjectName("lblError")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblError)
        self.lneError = QtWidgets.QLineEdit(self.centralwidget)
        self.lneError.setObjectName("lneError")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lneError)
        self.lblTrace = QtWidgets.QLabel(self.centralwidget)
        self.lblTrace.setObjectName("lblTrace")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTrace)
        self.lneTrace = QtWidgets.QLineEdit(self.centralwidget)
        self.lneTrace.setObjectName("lneTrace")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lneTrace)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lneDisplay.setText(_translate("MainWindow", "..........................................................................................................................................."))
        self.label.setText(_translate("MainWindow", "Брокер"))
        self.pbtnConnect.setText(_translate("MainWindow", "Підключено"))
        self.pbtnSettings.setText(_translate("MainWindow", "Налаштування"))
        self.lblControl.setText(_translate("MainWindow", "Контроль"))
        self.pbtnOnOff.setText(_translate("MainWindow", "Включено"))
        self.lblDisplay.setText(_translate("MainWindow", "Екран"))
        self.lblLuminocity.setText(_translate("MainWindow", "Освітлення:"))
        self.lblLux.setText(_translate("MainWindow", "Люкси"))
        self.lblPressure.setText(_translate("MainWindow", "Тиск:"))
        self.lblPascal.setText(_translate("MainWindow", " Мм рт ст"))
        self.lblTemperature.setText(_translate("MainWindow", "Температура:"))
        self.lblDegrees.setText(_translate("MainWindow", "Градуси"))
        self.lblState.setText(_translate("MainWindow", "Статус:"))
        self.lneState.setText(_translate("MainWindow", "Відключено"))
        self.lblError.setText(_translate("MainWindow", "Помилки:"))
        self.lneError.setText(_translate("MainWindow", "Помилки"))
        self.lblTrace.setText(_translate("MainWindow", "Інформація:"))
        self.lneTrace.setText(_translate("MainWindow", "Інформація"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
